namespace LeakChecker.DataParser.Content;

public enum ItemEnum
{
    // Control
    Previous,
    Empty,
    Null,
    
    // Content
    Ipv4,
    Ipv6,
    Mac,
    PhoneNumber,
    Email,
    Web,
    Timestamp,
    UnixSeconds,
    UnixMilliseconds,
    NetTicks,
    FileTime,
    Location,
    Organization,
    Name,
    FirstName,
    LastName,
    Gender,
    DateOfBirth,
    Age,
    Nationality,
    EyeColor,
    HairColor,
    Height,
    Weight,
    MaritalStatus,
    Iban,
    Username,
    Password,
    Salt,
    Token,
    Id,
    Other,
    
    ////////////////////////////////////////////
    //                Hash types              //
    ////////////////////////////////////////////
    //    "plaintext" is "pass" in hashcat    //
    ////////////////////////////////////////////
    
    // MD4
    MD4,
    
    // MD5
    MD5,
    HALF_MD5,
    MD5_MD5_PLAINTEXT,
    MD5_SHA1_PLAINTEXT,
    MD5_PLAINTEXT_SALT,
    MD5_SALT_PLAINTEXT,
    MD5_APR1,
    MD5_MD5_PLAINTEXT_MD5_SALT,
    MD5_SALT_MD5_PLAINTEXT_SALT,
    MD5_SHA1_SALT_MD5_PLAINTEXT,
    MD5_STRTOUPPER_MD5_PLAINTEXT,
    MD5_SALT_SHA1_SALT_PLAINTEXT,
    MD5_CRYPT,
    MD5_SHA1_PLAINTEXT_MD5_PLAINTEXT_SHA1_PLAINTEXT,

    // SHA1
    SHA1,
    SHA1_CX,
    SHA1_MD5_PLAINTEXT,
    SHA1_BASE64_NSLDAP,
    SSHA1_BASE64_NSLDAPS,
    SHA1_SALT_PLAINTEXT,
    SHA1_PLAINTEXT_SALT,
    SHA1_SALT_SHA1_PLAINTEXT_SALT,
    SHA1_UTF16LE_PLAINTEXT,
    SHA1_MD5_PLAINTEXT_SALT,
    SHA1_UTF16LE_PLAINTEXT_SALT,
    SHA1_SALT_UTF16LE_PLAINTEXT,
    SHA1_SUBSTR32,

    // SHA2
    SHA224,
    SHA256,
    SHA256_MD5_PLAINTEXT,
    SHA256_PLAINTEXT_SALT,
    SHA256_SALT_PLAINTEXT,
    SHA256_CRYPT,
    SHA256_SALT_PLAINTEXT_SALT,
    SHA256_SHA256_PLAINTEXT_SALT,
    SHA384,
    SHA512,
    SHA512_CRYPT,
    SHA512_PLAINTEXT_SALT,
    SHA512_SALT_PLAINTEXT,
    SSHA512_BASE64,
    
    // SHA3
    SHA3_224,
    SHA3_256,
    SHA3_384,
    SHA3_512,

    // KECCAK
    KECCAK224,
    KECCAK256,
    KECCAK384,
    KECCAK512,

    // HMAC
    HMAC_MD5_PLAINTEXT,
    HMAC_MD5_SALT,
    HMAC_SHA1_SALT,
    HMAC_SHA256_PLAINTEXT,
    HMAC_SHA256_SALT,
    HMAC_SHA256_SALT_PLAINTEXT_SECRET,
    HMAC_SHA512_PLAINTEXT,
    HMAC_SHA512_SALT,

    // PBKDF2
    PBKDF2_HMAC_MD5,
    PBKDF2_HMAC_SHA1,
    PBKDF2_HMAC_SHA256,
    PBKDF2_HMAC_SHA512,

    // BCRYPT
    BCRYPT_BLOWFISH_UNIX,
    BCRYPT_MD5,
    BCRYPT_SHA256,
    
    // LANMAN / NTLM
    LM,
    NTLM,

    // MySQL
    MYSQL323,
    MYSQL41_5,
    MYSQL_A_SHA256CRYPT,

    // MSSQL
    MSSQL2005,
    MSSQL2012_2014,
    
    // DJANGO
    DJANGO_SHA1,
    DJANGO_PBKDF2_SHA256,
    
    // PHPASS
    PHPBB3_MD5,
    PHPASS_WORDPRESS_MD5,
    
    // CMS
    JOOMLA_BEFORE_2_5_18,
    VBULLETIN_BEFORE_3_8_5,
    VBULLETIN_AFTER_3_8_5,
    MYBB_IPB2,
    
    // METAMASK WALLET
    METAMASK_WALLET,
    METAMASK_WALLET_SHORT,
    
    // ELECTRUM WALLET
    ELECTRUM_WALLET_1_3,
    ELECTRUM_WALLET_4,
    ELECTRUM_WALLET_5,
    
    // ETHEREUM WALLET
    ETHEREUM_WALLET_SCRYPT,
    ETHEREUM_WALLET_PBKDF2_HMAC_SHA256,
    ETHEREUM_PRE_SALE_WALLET_PBKDF2_HMAC_SHA256,
    
    // BITCOIN
    BITCOIN_PUBLIC_ADDRESS,
    LITECOIN_PUBLIC_ADDRESS,
    BITCOIN_CASH_PUBLIC_ADDRESS,
    BITCOIN_LITTLECOIN_WALLET_DAT,
    
    // BLOCKCHAIN
    BLOCKCHAIN_MY_WALLET,
    BLOCKCHAIN_MY_WALLET_V2,
    BLOCKCHAIN_MY_WALLET_SECOND_SHA256,
    
    // APPLE
    MACOS_V107,
    MACOS_V108_PBKDF2_SHA512,
    APPLE_KEYCHAIN,
    APPLE_SECURE_NOTES,
    APPLE_ITUNES_BACKUP_BEFORE_10_0,
    APPLE_ITUNES_BACKUP_AFTER_10_0,
    APPLE_FILE_SYSTEM,
    
    // PDF
    PDF_11_13_ACROBAT_2_4,
    PDF_11_13_ACROBAT_2_4_COLLIDER_1,
    PDF_11_13_ACROBAT_2_4_COLLIDER_2,
    PDF_14_16_ACROBAT_5_8,
    PDF_17_LEVEL_3_ACROBAT_9,
    PDF_17_LEVEL_8_ACROBAT_10_11,
    PDF_UNKNOWN_TYPE,
    
    // MS OFFICE
    MS_OFFICE_2007,
    MS_OFFICE_2010,
    MS_OFFICE_2013,
    MS_OFFICE_2016_SHEET_PROTECTION,
    MS_OFFICE_2003_MD5_RC4,
    MS_OFFICE_2003_MD5_RC4_COLLIDER_1,
    MS_OFFICE_2003_MD5_RC4_COLLIDER_2,
    MS_OFFICE_2003_SHA1_RC4,
    MS_OFFICE_2003_SHA1_RC4_COLLIDER_1,
    MS_OFFICE_2003_SHA1_RC4_COLLIDER_2,
    
    // KERBEROS
    KERBEROS_5_ETYPE_17_DB,
    KERBEROS_5_ETYPE_18_DB,
    KERBEROS_5_TGS_REP_ETYPE_23,
    KERBEROS_5_ETYPE_17_PRE_AUTH,
    KERBEROS_5_ETYPE_18_PRE_AUTH,
    KERBEROS_5_AS_REQ_PRE_AUTH_ETYPE_23,
    KERBEROS_5_ETYPE_17_TGS_REP_AES128_CTS_HMAC_SHA1_96,
    KERBEROS_5_ETYPE_18_TGS_REP_AES256_CTS_HMAC_SHA1_96,
    
    // PKZIP
    PKZIP_COMPRESSED,
    PKZIP_UNCOMPRESSED,
    PKZIP_COMPRESSED_MULTI_FILE,
    PKZIP_MIXED_MULTI_FILE,
    PKZIP_MIXED_MULTI_FILE_CHECKSUM_ONLY,
    
    // RSA/DSA/EC/OPENSSH
    RSA_DSA_EC_OPENSSH_PRIVATE_KEYS_0,
    RSA_DSA_EC_OPENSSH_PRIVATE_KEYS_6,
    RSA_DSA_EC_OPENSSH_PRIVATE_KEYS_1_3,
    RSA_DSA_EC_OPENSSH_PRIVATE_KEYS_4,
    RSA_DSA_EC_OPENSSH_PRIVATE_KEYS_5,
    
    // AXCRYPT
    AXCRYPT,
    AXCRYPT_INMEMORY_SHA1,
    
    // OTHERS
    JWT,
    PHPS,
    RAR5,
    RAR3_HP,
    RAR3_P_COMPRESSED,
    RAR3_P_UNCOMPRESSED,
    SEVENZIP,
    WINZIP,
    SCRYPT,
    DRUPAL7,
    RADMIN2,
    RADMIN3,
    OPENCART,
    WHIRLPOOL,
    BITLOCKER,
    NET_NTLM_V2,
    AIX_SSHA1,
    FILEVAULT_2,
    YESCRYPT,
    AUTHME_SHA256,
    ANSIBLE_VAULT,
    MOZILLA_KEY3_DB,
    MOZILLA_KEY4_DB,
    GOST_R_34_11_94,
    MULTIBIT_HD_SCRYPT,
    MULTIBIT_CLASSIC_KEY_MD5,
    MULTIBIT_CLASSIC_WALLET_SCRYPT,
    BASE64,
    PASSWORD_SAFE_V3,
    ANDROID_BACKUP,
    ANDROID_FDE_SAMSUNG_DEK,
    WPA_PMKID_PBKDF2,
    WPA_PBKDF2_PMKID_EAPOL,
    IPMI2_RAKP_HMAC_SHA1,
    OSCOMMERCE_XTCOMMERCE,
    CISCO_IOS_9_SCRYPT,
    CISCO_IOS_8_PBKDF2_SHA256,
    ATLASSIAN_PBKDF2_HMAC_SHA1,
    EXODUS_DESKTOP_WALLET_SCRYPT,
    BESTCRYPT_V3_VOLUME_ENCRYPTION,
    SMF_AFTER_1_1,
    RUBY_ON_RAILS_RESTFUL_AUTHENTICATION,
    GPG_AES_128_AES256_SHA1_PLAINTEXT,
    KEEPASS1_AES_TWOFISH_KEEPASS2_AES,
    TELEGRAM_DESKTOP_AFTER_V2114_PBKDF_HMAC_SHA1,
    PKCS8_PRIVATE_KEYS_PBKDF2_HMAC_SHA1_3DES_AES,
    PKCS8_PRIVATE_KEYS_PBKDF2_HMAC_SHA256_3DES_AES,
}
