using LeakChecker.Common.Enums;
using LeakChecker.DataParser.Format;

namespace LeakChecker.DataParser.Tests.Format;

public class HeaderGuesserTests
{
    // ---------------- IpV4 ----------------
    [Theory]
    [InlineData("ip", ItemType.Ipv4)]
    [InlineData("ip4", ItemType.Ipv4)]
    [InlineData("ipv4", ItemType.Ipv4)]
    [InlineData("IpV4", ItemType.Ipv4)]
    [InlineData("client_ip", ItemType.Ipv4)]
    [InlineData("player_ip", ItemType.Ipv4)]
    [InlineData("srcIp", ItemType.Ipv4)]
    [InlineData("server_ip4_addr", ItemType.Ipv4)]
    [InlineData("userIpV4", ItemType.Ipv4)]
    [InlineData("device-ip4", ItemType.Ipv4)]
    public void ShouldGuess_IpV4(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- IpV6 ----------------
    [Theory]
    [InlineData("ip6", ItemType.Ipv6)]
    [InlineData("ipv6", ItemType.Ipv6)]
    [InlineData("IpV6", ItemType.Ipv6)]
    [InlineData("client_ip6", ItemType.Ipv6)]
    [InlineData("sourceIp6", ItemType.Ipv6)]
    [InlineData("destinationIPV6", ItemType.Ipv6)]
    [InlineData("server_ip6_addr", ItemType.Ipv6)]
    [InlineData("userIpv6", ItemType.Ipv6)]
    [InlineData("device-ip6", ItemType.Ipv6)]
    [InlineData("networkIpv6", ItemType.Ipv6)]
    public void ShouldGuess_IpV6(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- Mac ----------------
    [Theory]
    [InlineData("mac", ItemType.MacAddress)]
    [InlineData("macaddr", ItemType.MacAddress)]
    [InlineData("mac_address", ItemType.MacAddress)]
    [InlineData("macAddress", ItemType.MacAddress)]
    [InlineData("MACADDRESS", ItemType.MacAddress)]
    [InlineData("device-mac", ItemType.MacAddress)]
    [InlineData("clientMacAddr", ItemType.MacAddress)]
    [InlineData("wifi_mac", ItemType.MacAddress)]
    [InlineData("ethernetMac", ItemType.MacAddress)]
    [InlineData("user-mac-address", ItemType.MacAddress)]
    public void ShouldGuess_Mac(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- TimeStamp ----------------
    [Theory]
    [InlineData("ts", ItemType.Timestamp)]
    [InlineData("time", ItemType.Timestamp)]
    [InlineData("timestamp", ItemType.Timestamp)]
    [InlineData("ban_created", ItemType.Timestamp)]
    [InlineData("updated", ItemType.Timestamp)]
    [InlineData("insertdate", ItemType.Timestamp)]
    [InlineData("date_time", ItemType.Timestamp)]
    [InlineData("lastModified", ItemType.Timestamp)]
    [InlineData("accountCreatedAt", ItemType.Timestamp)]
    [InlineData("user_insert_date", ItemType.Timestamp)]
    public void ShouldGuess_TimeStamp(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- Location ----------------
    [Theory]
    [InlineData("location", ItemType.Location)]
    [InlineData("latitude", ItemType.Location)]
    [InlineData("longitude", ItemType.Location)]
    [InlineData("latlng", ItemType.Location)]
    [InlineData("address", ItemType.Location)]
    [InlineData("city", ItemType.Location)]
    [InlineData("country", ItemType.Location)]
    [InlineData("state", ItemType.Location)]
    [InlineData("region", ItemType.Location)]
    [InlineData("user_location", ItemType.Location)]
    public void ShouldGuess_Location(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- PhoneNumber ----------------
    [Theory]
    [InlineData("phone", ItemType.PhoneNumber)]
    [InlineData("phonenumber", ItemType.PhoneNumber)]
    [InlineData("phone_number", ItemType.PhoneNumber)]
    [InlineData("mobile", ItemType.PhoneNumber)]
    [InlineData("mobilephone", ItemType.PhoneNumber)]
    [InlineData("telephone", ItemType.PhoneNumber)]
    [InlineData("cell", ItemType.PhoneNumber)]
    [InlineData("userPhone", ItemType.PhoneNumber)]
    [InlineData("contact_phone", ItemType.PhoneNumber)]
    [InlineData("user-mobile-phone", ItemType.PhoneNumber)]
    public void ShouldGuess_PhoneNumber(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- Email ----------------
    [Theory]
    [InlineData("email", ItemType.Email)]
    [InlineData("e-mail", ItemType.Email)]
    [InlineData("e_mail", ItemType.Email)]
    [InlineData("mail", ItemType.Email)]
    [InlineData("userEmail", ItemType.Email)]
    [InlineData("account-mail", ItemType.Email)]
    [InlineData("contact_email", ItemType.Email)]
    [InlineData("EMAIL", ItemType.Email)]
    [InlineData("primaryEmail", ItemType.Email)]
    [InlineData("customer_mail_addr", ItemType.Email)]
    public void ShouldGuess_Email(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- Iban ----------------
    [Theory]
    [InlineData("iban", ItemType.Iban)]
    [InlineData("bankaccount", ItemType.Iban)]
    [InlineData("bank_account", ItemType.Iban)]
    [InlineData("bank-account", ItemType.Iban)]
    [InlineData("userIban", ItemType.Iban)]
    [InlineData("client_iban", ItemType.Iban)]
    [InlineData("paymentIban", ItemType.Iban)]
    [InlineData("IBAN", ItemType.Iban)]
    [InlineData("iban_number", ItemType.Iban)]
    [InlineData("recipientBankAccount", ItemType.Iban)]
    public void ShouldGuess_Iban(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- Gender ----------------
    [Theory]
    [InlineData("gender", ItemType.Gender)]
    [InlineData("userGender", ItemType.Gender)]
    [InlineData("user_gender", ItemType.Gender)]
    [InlineData("GENDER", ItemType.Gender)]
    [InlineData("account-gender", ItemType.Gender)]
    [InlineData("sex", ItemType.Gender)]
    [InlineData("usersex", ItemType.Gender)]
    [InlineData("biological_gender", ItemType.Gender)]
    [InlineData("UserGenderCode", ItemType.Gender)]
    [InlineData("profile_gender_value", ItemType.Gender)]
    public void ShouldGuess_Gender(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- Name ----------------
    [Theory]
    // 10 all-lowercase
    [InlineData("name", ItemType.Name)]
    [InlineData("firstname", ItemType.Name)]
    [InlineData("lastname", ItemType.Name)]
    [InlineData("givenname", ItemType.Name)]
    [InlineData("realname", ItemType.Name)]
    [InlineData("legalname", ItemType.Name)]
    [InlineData("surname", ItemType.Name)]
    [InlineData("fullname", ItemType.Name)]
    [InlineData("person", ItemType.Name)]
    [InlineData("customername", ItemType.Name)]
    // 20 snake_case
    [InlineData("first_name", ItemType.Name)]
    [InlineData("last_name", ItemType.Name)]
    [InlineData("full_name", ItemType.Name)]
    [InlineData("given_name", ItemType.Name)]
    [InlineData("family_name", ItemType.Name)]
    [InlineData("middle_name", ItemType.Name)]
    [InlineData("name_prefix", ItemType.Name)]
    [InlineData("name_suffix", ItemType.Name)]
    [InlineData("user_name", ItemType.Name)]
    [InlineData("contact_name", ItemType.Name)]
    [InlineData("customer_full_name", ItemType.Name)]
    [InlineData("legal_full_name", ItemType.Name)]
    [InlineData("profile_full_name", ItemType.Name)]
    [InlineData("person_first_name", ItemType.Name)]
    [InlineData("person_last_name", ItemType.Name)]
    [InlineData("customer_given_name", ItemType.Name)]
    [InlineData("registered_first_name", ItemType.Name)]
    [InlineData("employee_surname", ItemType.Name)]
    [InlineData("contact_name_field", ItemType.Name)]
    [InlineData("billing_full_name", ItemType.Name)]
    // 5 camelCase
    [InlineData("firstName", ItemType.Name)]
    [InlineData("lastName", ItemType.Name)]
    [InlineData("fullName", ItemType.Name)]
    [InlineData("givenName", ItemType.Name)]
    [InlineData("userNameFull", ItemType.Name)]
    // 5 PascalCase
    [InlineData("FirstName", ItemType.Name)]
    [InlineData("LastName", ItemType.Name)]
    [InlineData("FullName", ItemType.Name)]
    [InlineData("GivenName", ItemType.Name)]
    [InlineData("UserNameFull", ItemType.Name)]
    public void ShouldGuess_Name(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- Username ----------------
    [Theory]
    // 10 all-lowercase
    [InlineData("username", ItemType.Username)]
    [InlineData("nickname", ItemType.Username)]
    [InlineData("alias", ItemType.Username)]
    [InlineData("nick", ItemType.Username)]
    [InlineData("loginname", ItemType.Username)]
    [InlineData("screenname", ItemType.Username)]
    [InlineData("nicename", ItemType.Username)]
    [InlineData("accountusername", ItemType.Username)]
    [InlineData("accountname", ItemType.Username)]
    [InlineData("usernick", ItemType.Username)]
    // 20 snake_case
    [InlineData("forum_user", ItemType.Username)]
    [InlineData("user_nicename", ItemType.Username)]
    [InlineData("user_login", ItemType.Username)]
    [InlineData("display_name", ItemType.Username)]
    [InlineData("nick_name", ItemType.Username)]
    [InlineData("account_nickname", ItemType.Username)]
    [InlineData("profile_nick", ItemType.Username)]
    [InlineData("forum_nickname", ItemType.Username)]
    [InlineData("account_nick", ItemType.Username)]
    [InlineData("user_alias", ItemType.Username)]
    [InlineData("login_name", ItemType.Username)]
    [InlineData("screen_name", ItemType.Username)]
    [InlineData("user_nickname", ItemType.Username)]
    [InlineData("account_nickname_value", ItemType.Username)]
    [InlineData("profile_username", ItemType.Username)]
    [InlineData("admin_nick", ItemType.Username)]
    [InlineData("user_display_name", ItemType.Username)]
    [InlineData("system_nickname", ItemType.Username)]
    [InlineData("client_nick", ItemType.Username)]
    [InlineData("account_username", ItemType.Username)]
    // 5 camelCase
    [InlineData("userName", ItemType.Username)]
    [InlineData("nickName", ItemType.Username)]
    [InlineData("displayName", ItemType.Username)]
    [InlineData("accountNickname", ItemType.Username)]
    [InlineData("profileNick", ItemType.Username)]
    // 5 PascalCase
    [InlineData("UserName", ItemType.Username)]
    [InlineData("NickName", ItemType.Username)]
    [InlineData("DisplayName", ItemType.Username)]
    [InlineData("AccountNickname", ItemType.Username)]
    [InlineData("ProfileNick", ItemType.Username)]
    public void ShouldGuess_Username(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- Password ----------------
    [Theory]
    // 10 all-lowercase
    [InlineData("pwd", ItemType.Password)]
    [InlineData("pass", ItemType.Password)]
    [InlineData("passwd", ItemType.Password)]
    [InlineData("password", ItemType.Password)]
    [InlineData("passcode", ItemType.Password)]
    [InlineData("passwordkey", ItemType.Password)]
    [InlineData("passwordvalue", ItemType.Password)]
    [InlineData("userpass", ItemType.Password)]
    [InlineData("userpassword", ItemType.Password)]
    [InlineData("loginpassword", ItemType.Password)]
    // 20 snake_case
    [InlineData("user_pass", ItemType.Password)]
    [InlineData("user_password", ItemType.Password)]
    [InlineData("account_pwd", ItemType.Password)]
    [InlineData("account_password", ItemType.Password)]
    [InlineData("pwd_value", ItemType.Password)]
    [InlineData("password_value", ItemType.Password)]
    [InlineData("passwd_string", ItemType.Password)]
    [InlineData("member_password", ItemType.Password)]
    [InlineData("security_pass", ItemType.Password)]
    [InlineData("user_passcode", ItemType.Password)]
    [InlineData("customer_passwd", ItemType.Password)]
    [InlineData("login_pass", ItemType.Password)]
    [InlineData("user_pwd", ItemType.Password)]
    [InlineData("user_passwd", ItemType.Password)]
    [InlineData("user_pass_phrase", ItemType.Password)]
    [InlineData("account_pass", ItemType.Password)]
    [InlineData("customer_pwd_value", ItemType.Password)]
    [InlineData("security_pwd_value", ItemType.Password)]
    [InlineData("user_password_value", ItemType.Password)]
    [InlineData("service_password", ItemType.Password)]
    // 5 camelCase
    [InlineData("userPassword", ItemType.Password)]
    [InlineData("accountPwd", ItemType.Password)]
    [InlineData("loginPass", ItemType.Password)]
    [InlineData("pwdValue", ItemType.Password)]
    [InlineData("userPass", ItemType.Password)]
    // 5 PascalCase
    [InlineData("UserPassword", ItemType.Password)]
    [InlineData("AccountPwd", ItemType.Password)]
    [InlineData("LoginPass", ItemType.Password)]
    [InlineData("PwdValue", ItemType.Password)]
    [InlineData("UserPass", ItemType.Password)]
    public void ShouldGuess_Password(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- Salt ----------------
    [Theory]
    [InlineData("salt", ItemType.Salt)]
    [InlineData("user_salt", ItemType.Salt)]
    [InlineData("passwordSalt", ItemType.Salt)]
    [InlineData("SALT", ItemType.Salt)]
    [InlineData("account-salt", ItemType.Salt)]
    [InlineData("saltValue", ItemType.Salt)]
    [InlineData("hash_salt", ItemType.Salt)]
    [InlineData("userKeySalt", ItemType.Salt)]
    [InlineData("key_salt", ItemType.Salt)]
    [InlineData("securitySalt", ItemType.Salt)]
    public void ShouldGuess_Salt(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- Token ----------------
    [Theory]
    [InlineData("refresh_access_token", ItemType.Token)]
    [InlineData("api_key", ItemType.Token)]
    [InlineData("user_api_key_value", ItemType.Token)]
    [InlineData("key", ItemType.Token)]
    [InlineData("access_token", ItemType.Token)]
    [InlineData("userToken", ItemType.Token)]
    [InlineData("auth_token", ItemType.Token)]
    [InlineData("TOKEN", ItemType.Token)]
    [InlineData("sessionKey", ItemType.Token)]
    [InlineData("client_api_key", ItemType.Token)]
    public void ShouldGuess_Token(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- Web ----------------
    [Theory]
    [InlineData("web", ItemType.Web)]
    [InlineData("webaddr", ItemType.Web)]
    [InlineData("reason_link", ItemType.Web)]
    [InlineData("url", ItemType.Web)]
    [InlineData("link", ItemType.Web)]
    [InlineData("site", ItemType.Web)]
    [InlineData("PhotoUrl", ItemType.Web)]
    [InlineData("page_url", ItemType.Web)]
    [InlineData("userWeb", ItemType.Web)]
    [InlineData("homepageLink", ItemType.Web)]
    public void ShouldGuess_Web(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- Id ----------------
    [Theory]
    [InlineData("id", ItemType.Id)]
    [InlineData("uid", ItemType.Id)]
    [InlineData("bhid", ItemType.Id)]
    [InlineData("userid", ItemType.Id)]
    [InlineData("user_id", ItemType.Id)]
    [InlineData("playerid", ItemType.Id)]
    [InlineData("player_id", ItemType.Id)]
    [InlineData("guid", ItemType.Id)]
    [InlineData("sessionId", ItemType.Id)]
    [InlineData("FacebookUserID", ItemType.Id)]
    public void ShouldGuess_Id(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));

    // ---------------- Other ----------------
    [Theory]
    // ---------------- Lowercase ----------------
    [InlineData("rowversion", ItemType.Other)]
    [InlineData("archivedflag", ItemType.Other)]
    [InlineData("synctype", ItemType.Other)]
    [InlineData("recordstatus", ItemType.Other)]
    [InlineData("batchnumber", ItemType.Other)]
    [InlineData("errorcode", ItemType.Other)]
    [InlineData("retrycount", ItemType.Other)]
    [InlineData("rowchecksum", ItemType.Other)]
    [InlineData("dataloader", ItemType.Other)]
    [InlineData("processingflag", ItemType.Other)]
    [InlineData("exportformat", ItemType.Other)]
    [InlineData("sourceref", ItemType.Other)]
    [InlineData("commenttext", ItemType.Other)]
    [InlineData("changereason", ItemType.Other)]
    [InlineData("systemnote", ItemType.Other)]
    [InlineData("internalref", ItemType.Other)]
    [InlineData("loadstatus", ItemType.Other)]
    [InlineData("dataquality", ItemType.Other)]
    [InlineData("recordscount", ItemType.Other)]
    [InlineData("syncmarker", ItemType.Other)]
    [InlineData("passphrasehint", ItemType.Other)]
    [InlineData("userkeyhint", ItemType.Other)]
    [InlineData("loginflag", ItemType.Other)]
    [InlineData("securelevel", ItemType.Other)]
    [InlineData("authmarker", ItemType.Other)]
    [InlineData("credentialnote", ItemType.Other)]
    [InlineData("secretlabel", ItemType.Other)]
    [InlineData("passwordinfoflag", ItemType.Other)]
    [InlineData("usersecuritytag", ItemType.Other)]
    [InlineData("accountIsLocked", ItemType.Other)]

    // ---------------- snake_case ----------------
    [InlineData("row_created_by", ItemType.Other)]
    [InlineData("row_updated_by", ItemType.Other)]
    [InlineData("source_system", ItemType.Other)]
    [InlineData("record_type", ItemType.Other)]
    [InlineData("revision_number", ItemType.Other)]
    [InlineData("is_deleted", ItemType.Other)]
    [InlineData("is_archived", ItemType.Other)]
    [InlineData("sync_status", ItemType.Other)]
    [InlineData("audit_log_ref", ItemType.Other)]
    [InlineData("checksum_value", ItemType.Other)]
    [InlineData("legacy_record_ref", ItemType.Other)]
    [InlineData("process_flag", ItemType.Other)]
    [InlineData("etl_run_ref", ItemType.Other)]
    [InlineData("transaction_ref", ItemType.Other)]
    [InlineData("display_order", ItemType.Other)]
    [InlineData("sort_index", ItemType.Other)]
    [InlineData("cache_tag", ItemType.Other)]
    [InlineData("meta_info", ItemType.Other)]
    [InlineData("description_text", ItemType.Other)]
    [InlineData("metadata_json", ItemType.Other)]
    [InlineData("user_passwrd_hint", ItemType.Other)]
    [InlineData("account_secure_flag", ItemType.Other)]
    [InlineData("password_status_flag", ItemType.Other)]
    [InlineData("login_auth_marker", ItemType.Other)]
    [InlineData("user_attr_label", ItemType.Other)]
    [InlineData("account_lock_status", ItemType.Other)]
    [InlineData("passphrase_helper_text", ItemType.Other)]
    [InlineData("user_secure_tag", ItemType.Other)]
    [InlineData("password_level_note", ItemType.Other)]
    [InlineData("credential_info_flag", ItemType.Other)]

    // ---------------- camelCase ----------------
    [InlineData("rowCreatedBy", ItemType.Other)]
    [InlineData("rowUpdatedBy", ItemType.Other)]
    [InlineData("sourceSystem", ItemType.Other)]
    [InlineData("recordType", ItemType.Other)]
    [InlineData("revisionNumber", ItemType.Other)]
    [InlineData("isDeleted", ItemType.Other)]
    [InlineData("isArchived", ItemType.Other)]
    [InlineData("syncStatus", ItemType.Other)]
    [InlineData("auditLogRef", ItemType.Other)]
    [InlineData("checksumValue", ItemType.Other)]
    [InlineData("legacyRecordRef", ItemType.Other)]
    [InlineData("processFlag", ItemType.Other)]
    [InlineData("etlRunRef", ItemType.Other)]
    [InlineData("transactionRef", ItemType.Other)]
    [InlineData("displayOrder", ItemType.Other)]
    [InlineData("sortIndex", ItemType.Other)]
    [InlineData("cacheTag", ItemType.Other)]
    [InlineData("extraInfo", ItemType.Other)]
    [InlineData("descriptionText", ItemType.Other)]
    [InlineData("metadataJson", ItemType.Other)]
    [InlineData("userPasswrdHint", ItemType.Other)]
    [InlineData("accountSecureFlag", ItemType.Other)]
    [InlineData("passwordStatusFlag", ItemType.Other)]
    [InlineData("loginAuthMarker", ItemType.Other)]
    [InlineData("userAttrLabel", ItemType.Other)]
    [InlineData("accountLockStatus", ItemType.Other)]
    [InlineData("passphraseHelperText", ItemType.Other)]
    [InlineData("userSecureTag", ItemType.Other)]
    [InlineData("passwordLevelNote", ItemType.Other)]
    [InlineData("credentialInfoFlag", ItemType.Other)]

    // ---------------- PascalCase ----------------
    [InlineData("RowCreatedBy", ItemType.Other)]
    [InlineData("RowUpdatedBy", ItemType.Other)]
    [InlineData("SourceSystem", ItemType.Other)]
    [InlineData("RecordType", ItemType.Other)]
    [InlineData("RevisionNumber", ItemType.Other)]
    [InlineData("IsDeleted", ItemType.Other)]
    [InlineData("IsArchived", ItemType.Other)]
    [InlineData("SyncStatus", ItemType.Other)]
    [InlineData("AuditLogRef", ItemType.Other)]
    [InlineData("ChecksumValue", ItemType.Other)]
    [InlineData("LegacyRecordRef", ItemType.Other)]
    [InlineData("ProcessFlag", ItemType.Other)]
    [InlineData("EtlRunRef", ItemType.Other)]
    [InlineData("TransactionRef", ItemType.Other)]
    [InlineData("DisplayOrder", ItemType.Other)]
    [InlineData("SortIndex", ItemType.Other)]
    [InlineData("CacheTag", ItemType.Other)]
    [InlineData("ExtraInfo", ItemType.Other)]
    [InlineData("DescriptionText", ItemType.Other)]
    [InlineData("MetadataJson", ItemType.Other)]
    [InlineData("UserPasswrdHint", ItemType.Other)]
    [InlineData("AccountSecureFlag", ItemType.Other)]
    [InlineData("PasswordStatusFlag", ItemType.Other)]
    [InlineData("LoginAuthMarker", ItemType.Other)]
    [InlineData("UserAttrLabel", ItemType.Other)]
    [InlineData("AccountLockStatus", ItemType.Other)]
    [InlineData("PassphraseHelperText", ItemType.Other)]
    [InlineData("UserSecureTag", ItemType.Other)]
    [InlineData("PasswordLevelNote", ItemType.Other)]
    [InlineData("CredentialInfoFlag", ItemType.Other)]
    public void ShouldGuess_Other(string header, ItemType expected)
        => Assert.Equal(expected, HeaderGuesser.GuessItem(header));
}
