using LeakChecker.Format;
using LeakChecker.Content;

namespace LeakProcessor.Tests.Format;

public class SqlHeaderGuesserTests
{
    // ---------------- IpV4 ----------------
    [Theory]
    [InlineData("ip", ItemEnum.Ipv4)]
    [InlineData("ip4", ItemEnum.Ipv4)]
    [InlineData("ipv4", ItemEnum.Ipv4)]
    [InlineData("IpV4", ItemEnum.Ipv4)]
    [InlineData("client_ip", ItemEnum.Ipv4)]
    [InlineData("player_ip", ItemEnum.Ipv4)]
    [InlineData("srcIp", ItemEnum.Ipv4)]
    [InlineData("server_ip4_addr", ItemEnum.Ipv4)]
    [InlineData("userIpV4", ItemEnum.Ipv4)]
    [InlineData("device-ip4", ItemEnum.Ipv4)]
    public void ShouldGuess_IpV4(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- IpV6 ----------------
    [Theory]
    [InlineData("ip6", ItemEnum.Ipv6)]
    [InlineData("ipv6", ItemEnum.Ipv6)]
    [InlineData("IpV6", ItemEnum.Ipv6)]
    [InlineData("client_ip6", ItemEnum.Ipv6)]
    [InlineData("sourceIp6", ItemEnum.Ipv6)]
    [InlineData("destinationIPV6", ItemEnum.Ipv6)]
    [InlineData("server_ip6_addr", ItemEnum.Ipv6)]
    [InlineData("userIpv6", ItemEnum.Ipv6)]
    [InlineData("device-ip6", ItemEnum.Ipv6)]
    [InlineData("networkIpv6", ItemEnum.Ipv6)]
    public void ShouldGuess_IpV6(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- Mac ----------------
    [Theory]
    [InlineData("mac", ItemEnum.Mac)]
    [InlineData("macaddr", ItemEnum.Mac)]
    [InlineData("mac_address", ItemEnum.Mac)]
    [InlineData("macAddress", ItemEnum.Mac)]
    [InlineData("MACADDRESS", ItemEnum.Mac)]
    [InlineData("device-mac", ItemEnum.Mac)]
    [InlineData("clientMacAddr", ItemEnum.Mac)]
    [InlineData("wifi_mac", ItemEnum.Mac)]
    [InlineData("ethernetMac", ItemEnum.Mac)]
    [InlineData("user-mac-address", ItemEnum.Mac)]
    public void ShouldGuess_Mac(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- TimeStamp ----------------
    [Theory]
    [InlineData("ts", ItemEnum.Timestamp)]
    [InlineData("time", ItemEnum.Timestamp)]
    [InlineData("timestamp", ItemEnum.Timestamp)]
    [InlineData("ban_created", ItemEnum.Timestamp)]
    [InlineData("updated", ItemEnum.Timestamp)]
    [InlineData("insertdate", ItemEnum.Timestamp)]
    [InlineData("date_time", ItemEnum.Timestamp)]
    [InlineData("lastModified", ItemEnum.Timestamp)]
    [InlineData("accountCreatedAt", ItemEnum.Timestamp)]
    [InlineData("user_insert_date", ItemEnum.Timestamp)]
    public void ShouldGuess_TimeStamp(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- Location ----------------
    [Theory]
    [InlineData("location", ItemEnum.Location)]
    [InlineData("latitude", ItemEnum.Location)]
    [InlineData("longitude", ItemEnum.Location)]
    [InlineData("latlng", ItemEnum.Location)]
    [InlineData("address", ItemEnum.Location)]
    [InlineData("city", ItemEnum.Location)]
    [InlineData("country", ItemEnum.Location)]
    [InlineData("state", ItemEnum.Location)]
    [InlineData("region", ItemEnum.Location)]
    [InlineData("user_location", ItemEnum.Location)]
    public void ShouldGuess_Location(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- PhoneNumber ----------------
    [Theory]
    [InlineData("phone", ItemEnum.PhoneNumber)]
    [InlineData("phonenumber", ItemEnum.PhoneNumber)]
    [InlineData("phone_number", ItemEnum.PhoneNumber)]
    [InlineData("mobile", ItemEnum.PhoneNumber)]
    [InlineData("mobilephone", ItemEnum.PhoneNumber)]
    [InlineData("telephone", ItemEnum.PhoneNumber)]
    [InlineData("cell", ItemEnum.PhoneNumber)]
    [InlineData("userPhone", ItemEnum.PhoneNumber)]
    [InlineData("contact_phone", ItemEnum.PhoneNumber)]
    [InlineData("user-mobile-phone", ItemEnum.PhoneNumber)]
    public void ShouldGuess_PhoneNumber(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- Email ----------------
    [Theory]
    [InlineData("email", ItemEnum.Email)]
    [InlineData("e-mail", ItemEnum.Email)]
    [InlineData("e_mail", ItemEnum.Email)]
    [InlineData("mail", ItemEnum.Email)]
    [InlineData("userEmail", ItemEnum.Email)]
    [InlineData("account-mail", ItemEnum.Email)]
    [InlineData("contact_email", ItemEnum.Email)]
    [InlineData("EMAIL", ItemEnum.Email)]
    [InlineData("primaryEmail", ItemEnum.Email)]
    [InlineData("customer_mail_addr", ItemEnum.Email)]
    public void ShouldGuess_Email(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- Iban ----------------
    [Theory]
    [InlineData("iban", ItemEnum.Iban)]
    [InlineData("bankaccount", ItemEnum.Iban)]
    [InlineData("bank_account", ItemEnum.Iban)]
    [InlineData("bank-account", ItemEnum.Iban)]
    [InlineData("userIban", ItemEnum.Iban)]
    [InlineData("client_iban", ItemEnum.Iban)]
    [InlineData("paymentIban", ItemEnum.Iban)]
    [InlineData("IBAN", ItemEnum.Iban)]
    [InlineData("iban_number", ItemEnum.Iban)]
    [InlineData("recipientBankAccount", ItemEnum.Iban)]
    public void ShouldGuess_Iban(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- Gender ----------------
    [Theory]
    [InlineData("gender", ItemEnum.Gender)]
    [InlineData("userGender", ItemEnum.Gender)]
    [InlineData("user_gender", ItemEnum.Gender)]
    [InlineData("GENDER", ItemEnum.Gender)]
    [InlineData("account-gender", ItemEnum.Gender)]
    [InlineData("sex", ItemEnum.Gender)]
    [InlineData("usersex", ItemEnum.Gender)]
    [InlineData("biological_gender", ItemEnum.Gender)]
    [InlineData("UserGenderCode", ItemEnum.Gender)]
    [InlineData("profile_gender_value", ItemEnum.Gender)]
    public void ShouldGuess_Gender(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- Name ----------------
    [Theory]
    // 10 all-lowercase
    [InlineData("name", ItemEnum.Name)]
    [InlineData("firstname", ItemEnum.Name)]
    [InlineData("lastname", ItemEnum.Name)]
    [InlineData("givenname", ItemEnum.Name)]
    [InlineData("realname", ItemEnum.Name)]
    [InlineData("legalname", ItemEnum.Name)]
    [InlineData("surname", ItemEnum.Name)]
    [InlineData("fullname", ItemEnum.Name)]
    [InlineData("person", ItemEnum.Name)]
    [InlineData("customername", ItemEnum.Name)]
    // 20 snake_case
    [InlineData("first_name", ItemEnum.Name)]
    [InlineData("last_name", ItemEnum.Name)]
    [InlineData("full_name", ItemEnum.Name)]
    [InlineData("given_name", ItemEnum.Name)]
    [InlineData("family_name", ItemEnum.Name)]
    [InlineData("middle_name", ItemEnum.Name)]
    [InlineData("name_prefix", ItemEnum.Name)]
    [InlineData("name_suffix", ItemEnum.Name)]
    [InlineData("user_name", ItemEnum.Name)]
    [InlineData("contact_name", ItemEnum.Name)]
    [InlineData("customer_full_name", ItemEnum.Name)]
    [InlineData("legal_full_name", ItemEnum.Name)]
    [InlineData("profile_full_name", ItemEnum.Name)]
    [InlineData("person_first_name", ItemEnum.Name)]
    [InlineData("person_last_name", ItemEnum.Name)]
    [InlineData("customer_given_name", ItemEnum.Name)]
    [InlineData("registered_first_name", ItemEnum.Name)]
    [InlineData("employee_surname", ItemEnum.Name)]
    [InlineData("contact_name_field", ItemEnum.Name)]
    [InlineData("billing_full_name", ItemEnum.Name)]
    // 5 camelCase
    [InlineData("firstName", ItemEnum.Name)]
    [InlineData("lastName", ItemEnum.Name)]
    [InlineData("fullName", ItemEnum.Name)]
    [InlineData("givenName", ItemEnum.Name)]
    [InlineData("userNameFull", ItemEnum.Name)]
    // 5 PascalCase
    [InlineData("FirstName", ItemEnum.Name)]
    [InlineData("LastName", ItemEnum.Name)]
    [InlineData("FullName", ItemEnum.Name)]
    [InlineData("GivenName", ItemEnum.Name)]
    [InlineData("UserNameFull", ItemEnum.Name)]
    public void ShouldGuess_Name(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- Username ----------------
    [Theory]
    // 10 all-lowercase
    [InlineData("username", ItemEnum.Username)]
    [InlineData("nickname", ItemEnum.Username)]
    [InlineData("alias", ItemEnum.Username)]
    [InlineData("nick", ItemEnum.Username)]
    [InlineData("loginname", ItemEnum.Username)]
    [InlineData("screenname", ItemEnum.Username)]
    [InlineData("nicename", ItemEnum.Username)]
    [InlineData("accountusername", ItemEnum.Username)]
    [InlineData("accountname", ItemEnum.Username)]
    [InlineData("usernick", ItemEnum.Username)]
    // 20 snake_case
    [InlineData("forum_user", ItemEnum.Username)]
    [InlineData("user_nicename", ItemEnum.Username)]
    [InlineData("user_login", ItemEnum.Username)]
    [InlineData("display_name", ItemEnum.Username)]
    [InlineData("nick_name", ItemEnum.Username)]
    [InlineData("account_nickname", ItemEnum.Username)]
    [InlineData("profile_nick", ItemEnum.Username)]
    [InlineData("forum_nickname", ItemEnum.Username)]
    [InlineData("account_nick", ItemEnum.Username)]
    [InlineData("user_alias", ItemEnum.Username)]
    [InlineData("login_name", ItemEnum.Username)]
    [InlineData("screen_name", ItemEnum.Username)]
    [InlineData("user_nickname", ItemEnum.Username)]
    [InlineData("account_nickname_value", ItemEnum.Username)]
    [InlineData("profile_username", ItemEnum.Username)]
    [InlineData("admin_nick", ItemEnum.Username)]
    [InlineData("user_display_name", ItemEnum.Username)]
    [InlineData("system_nickname", ItemEnum.Username)]
    [InlineData("client_nick", ItemEnum.Username)]
    [InlineData("account_username", ItemEnum.Username)]
    // 5 camelCase
    [InlineData("userName", ItemEnum.Username)]
    [InlineData("nickName", ItemEnum.Username)]
    [InlineData("displayName", ItemEnum.Username)]
    [InlineData("accountNickname", ItemEnum.Username)]
    [InlineData("profileNick", ItemEnum.Username)]
    // 5 PascalCase
    [InlineData("UserName", ItemEnum.Username)]
    [InlineData("NickName", ItemEnum.Username)]
    [InlineData("DisplayName", ItemEnum.Username)]
    [InlineData("AccountNickname", ItemEnum.Username)]
    [InlineData("ProfileNick", ItemEnum.Username)]
    public void ShouldGuess_Username(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- Password ----------------
    [Theory]
    // 10 all-lowercase
    [InlineData("pwd", ItemEnum.Password)]
    [InlineData("pass", ItemEnum.Password)]
    [InlineData("passwd", ItemEnum.Password)]
    [InlineData("password", ItemEnum.Password)]
    [InlineData("passcode", ItemEnum.Password)]
    [InlineData("passwordkey", ItemEnum.Password)]
    [InlineData("passwordvalue", ItemEnum.Password)]
    [InlineData("userpass", ItemEnum.Password)]
    [InlineData("userpassword", ItemEnum.Password)]
    [InlineData("loginpassword", ItemEnum.Password)]
    // 20 snake_case
    [InlineData("user_pass", ItemEnum.Password)]
    [InlineData("user_password", ItemEnum.Password)]
    [InlineData("account_pwd", ItemEnum.Password)]
    [InlineData("account_password", ItemEnum.Password)]
    [InlineData("pwd_value", ItemEnum.Password)]
    [InlineData("password_value", ItemEnum.Password)]
    [InlineData("passwd_string", ItemEnum.Password)]
    [InlineData("member_password", ItemEnum.Password)]
    [InlineData("security_pass", ItemEnum.Password)]
    [InlineData("user_passcode", ItemEnum.Password)]
    [InlineData("customer_passwd", ItemEnum.Password)]
    [InlineData("login_pass", ItemEnum.Password)]
    [InlineData("user_pwd", ItemEnum.Password)]
    [InlineData("user_passwd", ItemEnum.Password)]
    [InlineData("user_pass_phrase", ItemEnum.Password)]
    [InlineData("account_pass", ItemEnum.Password)]
    [InlineData("customer_pwd_value", ItemEnum.Password)]
    [InlineData("security_pwd_value", ItemEnum.Password)]
    [InlineData("user_password_value", ItemEnum.Password)]
    [InlineData("service_password", ItemEnum.Password)]
    // 5 camelCase
    [InlineData("userPassword", ItemEnum.Password)]
    [InlineData("accountPwd", ItemEnum.Password)]
    [InlineData("loginPass", ItemEnum.Password)]
    [InlineData("pwdValue", ItemEnum.Password)]
    [InlineData("userPass", ItemEnum.Password)]
    // 5 PascalCase
    [InlineData("UserPassword", ItemEnum.Password)]
    [InlineData("AccountPwd", ItemEnum.Password)]
    [InlineData("LoginPass", ItemEnum.Password)]
    [InlineData("PwdValue", ItemEnum.Password)]
    [InlineData("UserPass", ItemEnum.Password)]
    public void ShouldGuess_Password(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- Salt ----------------
    [Theory]
    [InlineData("salt", ItemEnum.Salt)]
    [InlineData("user_salt", ItemEnum.Salt)]
    [InlineData("passwordSalt", ItemEnum.Salt)]
    [InlineData("SALT", ItemEnum.Salt)]
    [InlineData("account-salt", ItemEnum.Salt)]
    [InlineData("saltValue", ItemEnum.Salt)]
    [InlineData("hash_salt", ItemEnum.Salt)]
    [InlineData("userKeySalt", ItemEnum.Salt)]
    [InlineData("key_salt", ItemEnum.Salt)]
    [InlineData("securitySalt", ItemEnum.Salt)]
    public void ShouldGuess_Salt(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- Token ----------------
    [Theory]
    [InlineData("refresh_access_token", ItemEnum.Token)]
    [InlineData("api_key", ItemEnum.Token)]
    [InlineData("user_api_key_value", ItemEnum.Token)]
    [InlineData("key", ItemEnum.Token)]
    [InlineData("access_token", ItemEnum.Token)]
    [InlineData("userToken", ItemEnum.Token)]
    [InlineData("auth_token", ItemEnum.Token)]
    [InlineData("TOKEN", ItemEnum.Token)]
    [InlineData("sessionKey", ItemEnum.Token)]
    [InlineData("client_api_key", ItemEnum.Token)]
    public void ShouldGuess_Token(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- Web ----------------
    [Theory]
    [InlineData("web", ItemEnum.Web)]
    [InlineData("webaddr", ItemEnum.Web)]
    [InlineData("reason_link", ItemEnum.Web)]
    [InlineData("url", ItemEnum.Web)]
    [InlineData("link", ItemEnum.Web)]
    [InlineData("site", ItemEnum.Web)]
    [InlineData("PhotoUrl", ItemEnum.Web)]
    [InlineData("page_url", ItemEnum.Web)]
    [InlineData("userWeb", ItemEnum.Web)]
    [InlineData("homepageLink", ItemEnum.Web)]
    public void ShouldGuess_Web(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- Id ----------------
    [Theory]
    [InlineData("id", ItemEnum.Id)]
    [InlineData("uid", ItemEnum.Id)]
    [InlineData("bhid", ItemEnum.Id)]
    [InlineData("userid", ItemEnum.Id)]
    [InlineData("user_id", ItemEnum.Id)]
    [InlineData("playerid", ItemEnum.Id)]
    [InlineData("player_id", ItemEnum.Id)]
    [InlineData("guid", ItemEnum.Id)]
    [InlineData("sessionId", ItemEnum.Id)]
    [InlineData("FacebookUserID", ItemEnum.Id)]
    public void ShouldGuess_Id(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));

    // ---------------- Other ----------------
    [Theory]
    // ---------------- Lowercase ----------------
    [InlineData("rowversion", ItemEnum.Other)]
    [InlineData("archivedflag", ItemEnum.Other)]
    [InlineData("synctype", ItemEnum.Other)]
    [InlineData("recordstatus", ItemEnum.Other)]
    [InlineData("batchnumber", ItemEnum.Other)]
    [InlineData("errorcode", ItemEnum.Other)]
    [InlineData("retrycount", ItemEnum.Other)]
    [InlineData("rowchecksum", ItemEnum.Other)]
    [InlineData("dataloader", ItemEnum.Other)]
    [InlineData("processingflag", ItemEnum.Other)]
    [InlineData("exportformat", ItemEnum.Other)]
    [InlineData("sourceref", ItemEnum.Other)]
    [InlineData("commenttext", ItemEnum.Other)]
    [InlineData("changereason", ItemEnum.Other)]
    [InlineData("systemnote", ItemEnum.Other)]
    [InlineData("internalref", ItemEnum.Other)]
    [InlineData("loadstatus", ItemEnum.Other)]
    [InlineData("dataquality", ItemEnum.Other)]
    [InlineData("recordscount", ItemEnum.Other)]
    [InlineData("syncmarker", ItemEnum.Other)]
    [InlineData("passphrasehint", ItemEnum.Other)]
    [InlineData("userkeyhint", ItemEnum.Other)]
    [InlineData("loginflag", ItemEnum.Other)]
    [InlineData("securelevel", ItemEnum.Other)]
    [InlineData("authmarker", ItemEnum.Other)]
    [InlineData("credentialnote", ItemEnum.Other)]
    [InlineData("secretlabel", ItemEnum.Other)]
    [InlineData("passwordinfoflag", ItemEnum.Other)]
    [InlineData("usersecuritytag", ItemEnum.Other)]
    [InlineData("accountIsLocked", ItemEnum.Other)]

    // ---------------- snake_case ----------------
    [InlineData("row_created_by", ItemEnum.Other)]
    [InlineData("row_updated_by", ItemEnum.Other)]
    [InlineData("source_system", ItemEnum.Other)]
    [InlineData("record_type", ItemEnum.Other)]
    [InlineData("revision_number", ItemEnum.Other)]
    [InlineData("is_deleted", ItemEnum.Other)]
    [InlineData("is_archived", ItemEnum.Other)]
    [InlineData("sync_status", ItemEnum.Other)]
    [InlineData("audit_log_ref", ItemEnum.Other)]
    [InlineData("checksum_value", ItemEnum.Other)]
    [InlineData("legacy_record_ref", ItemEnum.Other)]
    [InlineData("process_flag", ItemEnum.Other)]
    [InlineData("etl_run_ref", ItemEnum.Other)]
    [InlineData("transaction_ref", ItemEnum.Other)]
    [InlineData("display_order", ItemEnum.Other)]
    [InlineData("sort_index", ItemEnum.Other)]
    [InlineData("cache_tag", ItemEnum.Other)]
    [InlineData("meta_info", ItemEnum.Other)]
    [InlineData("description_text", ItemEnum.Other)]
    [InlineData("metadata_json", ItemEnum.Other)]
    [InlineData("user_passwrd_hint", ItemEnum.Other)]
    [InlineData("account_secure_flag", ItemEnum.Other)]
    [InlineData("password_status_flag", ItemEnum.Other)]
    [InlineData("login_auth_marker", ItemEnum.Other)]
    [InlineData("user_attr_label", ItemEnum.Other)]
    [InlineData("account_lock_status", ItemEnum.Other)]
    [InlineData("passphrase_helper_text", ItemEnum.Other)]
    [InlineData("user_secure_tag", ItemEnum.Other)]
    [InlineData("password_level_note", ItemEnum.Other)]
    [InlineData("credential_info_flag", ItemEnum.Other)]

    // ---------------- camelCase ----------------
    [InlineData("rowCreatedBy", ItemEnum.Other)]
    [InlineData("rowUpdatedBy", ItemEnum.Other)]
    [InlineData("sourceSystem", ItemEnum.Other)]
    [InlineData("recordType", ItemEnum.Other)]
    [InlineData("revisionNumber", ItemEnum.Other)]
    [InlineData("isDeleted", ItemEnum.Other)]
    [InlineData("isArchived", ItemEnum.Other)]
    [InlineData("syncStatus", ItemEnum.Other)]
    [InlineData("auditLogRef", ItemEnum.Other)]
    [InlineData("checksumValue", ItemEnum.Other)]
    [InlineData("legacyRecordRef", ItemEnum.Other)]
    [InlineData("processFlag", ItemEnum.Other)]
    [InlineData("etlRunRef", ItemEnum.Other)]
    [InlineData("transactionRef", ItemEnum.Other)]
    [InlineData("displayOrder", ItemEnum.Other)]
    [InlineData("sortIndex", ItemEnum.Other)]
    [InlineData("cacheTag", ItemEnum.Other)]
    [InlineData("extraInfo", ItemEnum.Other)]
    [InlineData("descriptionText", ItemEnum.Other)]
    [InlineData("metadataJson", ItemEnum.Other)]
    [InlineData("userPasswrdHint", ItemEnum.Other)]
    [InlineData("accountSecureFlag", ItemEnum.Other)]
    [InlineData("passwordStatusFlag", ItemEnum.Other)]
    [InlineData("loginAuthMarker", ItemEnum.Other)]
    [InlineData("userAttrLabel", ItemEnum.Other)]
    [InlineData("accountLockStatus", ItemEnum.Other)]
    [InlineData("passphraseHelperText", ItemEnum.Other)]
    [InlineData("userSecureTag", ItemEnum.Other)]
    [InlineData("passwordLevelNote", ItemEnum.Other)]
    [InlineData("credentialInfoFlag", ItemEnum.Other)]

    // ---------------- PascalCase ----------------
    [InlineData("RowCreatedBy", ItemEnum.Other)]
    [InlineData("RowUpdatedBy", ItemEnum.Other)]
    [InlineData("SourceSystem", ItemEnum.Other)]
    [InlineData("RecordType", ItemEnum.Other)]
    [InlineData("RevisionNumber", ItemEnum.Other)]
    [InlineData("IsDeleted", ItemEnum.Other)]
    [InlineData("IsArchived", ItemEnum.Other)]
    [InlineData("SyncStatus", ItemEnum.Other)]
    [InlineData("AuditLogRef", ItemEnum.Other)]
    [InlineData("ChecksumValue", ItemEnum.Other)]
    [InlineData("LegacyRecordRef", ItemEnum.Other)]
    [InlineData("ProcessFlag", ItemEnum.Other)]
    [InlineData("EtlRunRef", ItemEnum.Other)]
    [InlineData("TransactionRef", ItemEnum.Other)]
    [InlineData("DisplayOrder", ItemEnum.Other)]
    [InlineData("SortIndex", ItemEnum.Other)]
    [InlineData("CacheTag", ItemEnum.Other)]
    [InlineData("ExtraInfo", ItemEnum.Other)]
    [InlineData("DescriptionText", ItemEnum.Other)]
    [InlineData("MetadataJson", ItemEnum.Other)]
    [InlineData("UserPasswrdHint", ItemEnum.Other)]
    [InlineData("AccountSecureFlag", ItemEnum.Other)]
    [InlineData("PasswordStatusFlag", ItemEnum.Other)]
    [InlineData("LoginAuthMarker", ItemEnum.Other)]
    [InlineData("UserAttrLabel", ItemEnum.Other)]
    [InlineData("AccountLockStatus", ItemEnum.Other)]
    [InlineData("PassphraseHelperText", ItemEnum.Other)]
    [InlineData("UserSecureTag", ItemEnum.Other)]
    [InlineData("PasswordLevelNote", ItemEnum.Other)]
    [InlineData("CredentialInfoFlag", ItemEnum.Other)]
    public void ShouldGuess_Other(string header, ItemEnum expected)
        => Assert.Equal(expected, SqlHeaderGuesser.GuessItem(header));
}
